config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#             event_tickets GET    /events/:event_id/tickets(.:format)                                                      tickets#index
#                           POST   /events/:event_id/tickets(.:format)                                                      tickets#create
#          new_event_ticket GET    /events/:event_id/tickets/new(.:format)                                                  tickets#new
#         edit_event_ticket GET    /events/:event_id/tickets/:id/edit(.:format)                                             tickets#edit
#              event_ticket GET    /events/:event_id/tickets/:id(.:format)                                                  tickets#show
#                           PATCH  /events/:event_id/tickets/:id(.:format)                                                  tickets#update
#                           PUT    /events/:event_id/tickets/:id(.:format)                                                  tickets#update
#                           DELETE /events/:event_id/tickets/:id(.:format)                                                  tickets#destroy
#                    events GET    /events(.:format)                                                                        events#index
#                           POST   /events(.:format)                                                                        events#create
#                 new_event GET    /events/new(.:format)                                                                    events#new
#                edit_event GET    /events/:id/edit(.:format)                                                               events#edit
#                     event GET    /events/:id(.:format)                                                                    events#show
#                           PATCH  /events/:id(.:format)                                                                    events#update
#                           PUT    /events/:id(.:format)                                                                    events#update
#                           DELETE /events/:id(.:format)                                                                    events#destroy
#                      root GET    /                                                                                        welcome#index
#                           GET    /auth/:provider/callback(.:format)                                                       session#create
#                    logout DELETE /logout(.:format)                                                                        session#destroy
#               retirements GET    /retirements(.:format)                                                                   retirements#index
#                           POST   /retirements(.:format)                                                                   retirements#create
#            new_retirement GET    /retirements/new(.:format)                                                               retirements#new
#           edit_retirement GET    /retirements/:id/edit(.:format)                                                          retirements#edit
#                retirement GET    /retirements/:id(.:format)                                                               retirements#show
#                           PATCH  /retirements/:id(.:format)                                                               retirements#update
#                           PUT    /retirements/:id(.:format)                                                               retirements#update
#                           DELETE /retirements/:id(.:format)                                                               retirements#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :events do
    resources :tickets
  end
  root 'welcome#index'
  get "/auth/:provider/callback" => "session#create"
  delete "/logout" => "session#destroy"

  resources :retirements
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  end_at     :datetime         not null
#  name       :string           not null
#  place      :string           not null
#  start_at   :datetime         not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :bigint           not null
#
# Indexes
#
#  index_events_on_owner_id  (owner_id)
#
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :tickets, dependent: :destroy

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at
  validates :start_at, presence: true

  def created_by?(user)
    owner_id === user.id
  end 
  private 

  def start_at_should_be_before_end_at
    if start_at >= end_at
      errors.add(:start_at, "は終了時間より前に設定してください")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: "作成しました"
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "更新しました"
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: "削除しました"
  end

  private 
  
  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_at, :end_at
    )
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

app/views/events/edit.html.haml
- now = Time.zone.now

%h1.mt-2 イベント編集

= form_with(model: @event, class: "form-group") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", row: 10
  = f.submit class: "btn btn-primary"

app/views/events/index.html.haml
%h1 イベント一覧

%ul.list-group
  - @events.each do |event|
    = link_to(event, class: "list-group-item list-group-item-action") do
      %h5.list-group-item-heading= event.name
      %p.mb-1= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}"

app/views/events/new.html.haml
- now = Time.zone.now

%h1.mt-2 イベント作成

= form_with(model: @event, class: "form-group") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", row: 10
  = f.submit class: "btn btn-primary"

app/views/events/show.html.haml
%h1.mt-3.mb-3= @event.name
.row
  .col-8
    .card.mb-2
      %h5.card-header イベント内容
      .card-body
        %p.card-text= @event.content
    .card.mb-2
      %h5.card-header 開催時間
      .card-body
        %p.card-text= "#{l(@event.start_at, format: :long) } - #{l(@event.end_at, format: :long)}"
    .card.mb-2
      %h5.card-header 開催場所
      .card-body
        %p.card-text= @event.place
    .card.mb-2
      %h5.card-header 主催者
      .card-body
        - if @event.owner
          = link_to("https://github.com/#{@event.owner.name}", class: "card-link") do
            = image_tag @event.owner.image_url, width: 50, height: 50
            = "#{@event.owner.name}"
        - else
          退会したユーザーです
  .col-4
    - if @event.created_by?(current_user)
      = link_to "イベントを編集する", edit_event_path(@event), class: "btn btn-info btn-block m-1"
      = link_to "イベントを削除する", event_path(@event), class: "btn btn-danger btn-block m-1", method: :delete, data: { confirm: "本当に削除して良いですか？"}
    - if @ticket
      = link_to("参加をキャンセルする", event_ticket_path(@event, @ticket), method: :delete, class: "btn btn-warning btn-block m-1")
    - elsif logged_in?
      %button.btn.btn-primary.btn-block.m-1{ "data-toggle": "modal", "data-target": "#createTicket" }
        参加する
      %div.modal.fade#createTicket
        .modal-dialog
          .modal-content
            .modal-header
              %h4.modal-title#dialogHeader 参加コメント
              %button.close{ type: "button", "data-dismiss": "modal" } &times;
            = form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f|
              .modal-body
                #createTicketErrors
                = f.text_field :comment, class: "form-control"
              .modal-footer
                %button.btn.btn-default{ type: "button", "data-dismiss": "modal" }
                  キャンセル
                = f.button "送信", class: "btn btn-primary"
    - else
      = link_to "参加する", new_event_ticket_path(@event), class: "btn btn-primary btn-block m-1"
    %hr
    .card.mb-2
      %h5.card-header 参加者
      %ul.list-group.list-group-flush
        - @tickets.each do |ticket|
          %li.list-group-item
            - if ticket.user
              = link_to(url_for_github(ticket.user), class: "card-link") do
                = image_tag ticket.user.image_url, width: 20, height: 20
                = "#{ticket.user.name}"
              = ticket.comment
            - else
              退会したユーザーです

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"